[package]
name = "journal-web-interface"
description = "Provides a web interface for journalctl"
version = "0.1.0"
authors = ["Adam Reichold <adam.reichold@uba.de>"]
license = "GPL-3.0"
repository = "https://gitlab.opencode.de/umwelt-info/journal-web-interface"
edition = "2021"

[dependencies]
hyper = { version = "0.14", features = ["http1", "server", "tcp", "stream"] }
form_urlencoded = "1.1"
tokio = { version = "1.0", features = ["macros", "rt", "process"] }
tokio-util = { version = "0.7", features = ["io"] }

[package.metadata.deb]
maintainer-scripts = "deployment"
assets = [
    ["target/release/journal-web-interface", "usr/bin/", "755"],
    ["deployment/journal-web-interface.service", "etc/systemd/system/", "644"],
]
